### ISSUE TITLE
appropriately deal with CORS

### ISSUE THREAD

**Issue by pipauwel** [LBDserver/front-react#8]
The code should handle CORS matters itself - and no external plugins should be needed to go around this.

**Comment by JWerbrouck** [comment]
Should be fixed (backend). For development, all origins are allowed. To set a single origin, comment out ```app.use(cors())``` in (backend)/src/app.ts and uncomment ```app.use(cors({origin: process.env.FRONT_END_URL}))```. A FRONT_END_URL environment variable has been provided in the dev.env.template, although a hardcoded origin will work as well.
